            - name: Run pytest
  # You may pin to the exact commit or the version.
  uses: pavelzw/pytest-action@v2.1.0
  with:
    job-summary: true
    verbose: true
    emoji: true
    report-title: "test report :)"
    click-to-expand: true
          
